import { makeStyles } from "@material-ui/core";

export const useStyles = makeStyles((theme) => ({
  outerContainer: {
    boxSizing: "border-box",
    margin: "0px auto",
    minWidth: 0,
    width: "100%",
    maxWidth: 1600,
    paddingLeft: 24,
    paddingRight: 24,
    flex: "1 1 0%",
    display: "grid",
    gap: 32,
    padding: "24px",
    minHeight: "90vh",

    [theme.breakpoints.down("sm")]: {
      border: "1 px solid black",
      borderRadius: "20px",
      boxShadow: "0px -8px 14px 0px rgb(229, 224, 224)",
    },
  },
  leftGrid: {
    boxSizing: "border-box",
    margin: 0,
    minWidth: 0,
    [theme.breakpoints.down("sm")]: {
      position: "relative",
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      textAlign: "center",
    },
  },
  rightGrid: {
    boxSizing: "border-box",
    margin: 0,
    minWidth: 0,
    display: "grid",
    gap: 24,
    justifyContent: "center",
    [theme.breakpoints.down("sm")]: {
      display: "flex",
    },
  },

  // address: {
  //   marginBottom: "36px",
  //   marginTop: "26px",
  //   display: "flex",
  // },
  name: {
    fonSize: "46px",
    marginTop: 20,
    marginBottom: "26px",
  },
  nameGrid: {
    width: "100%",
  },
  tag: {
    fontSize: "36px",
    boxSizing: "border-box",
    margin: 0,
    color: "transparent",
    minWidth: 0,
    textTransform: "capitalize",
    fontWeight: 600,
    background:
      "linear-gradient(110.78deg,#76E650 -1.13%,#F9D649 15.22%,#F08E35 32.09%,#EC5157 48.96%,#FF18BD 67.94%,#1A4BFF 85.34%,#62D8F9 99.57%)",
    backgroundClip: "text",
    "-webkit-background-clip": "text",
  },
  followersCount: {
    boxSizing: "border-box",
    margin: 0,
    minWidth: 0,
    fontSize: "24px",
    fontWeight: 700,

    marginTop: "32px",
  },
  followers: {
    boxSizing: "border-box",
    margin: 0,
    minWidth: 0,
    fontSize: "18px",
    fontWeight: 500,
    color: "#7f7f7f",
  },

  twitterFollow: {
    marginTop: "40px",
    marginBottom: "20px",
    boxSizing: "border-box",
  },
  bio: {
    fontSize: "18px",
    fontWeight: 500,
    marginBottom: "10px",
  },
  link: {
    fontSize: "18px",
    fontWeight: 500,
  },
  biopara: {
    fontSize: "16px",
    fontWeight: 400,
    textAlign: "justify",
    lineHeight: 1.6,
  },
  hrefs: {
    fontSize: "18px",
    color: "black",
    fontWeight: 600,

    lineHeight: 1.6,
    textDecoration: "none",
  },
  web: {
    marginRight: "16px",
  },
  socialLinks: {
    display: "flex",
    alignItems: "center",
    marginTop: "15px",
    marginBottom: "0px",
    "&:hover": {
      transform: "translateY(-2px)",
    },
  },
  join: {
    fontSize: "18px",
    fontWeight: 500,
  },
  joined: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  twit: {
    textDecoration: "none",
    fontWeight: 500,
    color: "black",
    fontSize: "18px",
    marginRight: "5px",
    marginTop: "5px",
  },
  socialtwitter: {
    textDecoration: "none",
    fontWeight: 500,
    color: "black",
    fontSize: "18px",
    width: "100%",
    height: "40px",
    maxWidth: "19ch",
    display: "flex",
    alignItems: "center",
    padding: "4px",
    marginRight: "10px",
    marginLeft: "10px",
    marginTop: "10px",
    marginBottom: "10px",
    border: "1px solid #ffffff",
    borderRadius: "16px",
    boxShadow: "0px 10px 20px rgb(0 0 0 / 5%)",

    background: "#FFFFFF",
    "&:hover": {
      transform: "translateY(-2px)",
      boxShadow: "1px ​10px 9px rgb(10 7 6 / 20%)",
    },
    // justifyContent: "space-evenly",
  },
  datejoin: {
    marginTop: "30px",
    width: "100%",
    marginBottom: "20px",
  },
  bioGrid: {
    marginTop: "20px",
    width: "100%",
    marginBottom: "15px",
  },
  linkGrid: {
    marginTop: "0px",
    width: "100%",
    marginBottom: "15px",
  },
  startAddress: {
    border: "1px solid black",
    color: "white",
    background: "black",
    borderRadius: "14px",
    marginRight: "6px",

    [theme.breakpoints.down("sm")]: {
      border: "none",
      color: "black",
      background: "none",
    },
  },
  addressBtn: {
    textDecoration: "none",
    fontWeight: 500,
    color: "black",
    fontSize: "18px",
    width: "100%",
    height: "30px",
    maxWidth: "19ch",
    display: "flex",
    alignItems: "center",
    padding: "4px",
    marginRight: "10px",
    marginLeft: "10px",
    marginTop: "10px",
    marginBottom: "10px",
    border: "1px solid #ffffff",
    borderRadius: "16px",
    boxShadow: "0px 10px 20px rgb(0 0 0 / 5%)",
    background: "#FFFFFF",
    [theme.breakpoints.down("sm")]: {
      width: "100%",
      position: "absolute",
      top: "-50px",
      marginLeft: "auto",
      marginRight: "auto",
      left: 0,
      right: 0,
      textAlign: "center",
      justifyContent: "center",
    },

    // justifyContent: "space-evenly",
  },
  copyBtn: {
    cursor: "pointer",
    marginTop: "6px",
    color: "rgb(204 204 204)",
    "&:hover": {
      color: "black",
    },
  },
}));
